/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-02-09 07:53:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch08_005fboard_005fmodel1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;

public final class editForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


String DRIVER="com.mysql.jdbc.Driver";
String URL="jdbc:mysql://localhost:3306/mydb";
String USER="root";
String PWD="12345";

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

request.setCharacterEncoding("UTF-8");
String num=request.getParameter("num"); //content.jsp에서 넘겨준 num받기 

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <title>editForm.jsp</title>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  h2{text-align: center;}\r\n");
      out.write("  table{margin:auto; width: 500;}\r\n");
      out.write("  </style>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("   function check(){\r\n");
      out.write("\t   if(document.editForm.pw.value==''){\r\n");
      out.write("\t\t   alert(\"암호를 입력하세요\");\r\n");
      out.write("\t\t   document.editForm.pw.focus();\r\n");
      out.write("\t\t   return false;\r\n");
      out.write("\t   }//if-end\r\n");
      out.write("\t   document.editForm.action=\"editPro.jsp?num=");
      out.print(num);
      out.write("\"; \r\n");
      out.write("\t   document.editForm.submit(); //전송\r\n");
      out.write("   }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

Class.forName(DRIVER); //드라이버 로딩
Connection con=DriverManager.getConnection(URL,USER,PWD); //DB연결
Statement stmt=con.createStatement(); //Statement생성
String sql="select * from board2 where num="+num;
ResultSet rs=stmt.executeQuery(sql); //Statement는 실행시 인자 들어간다
while(rs.next()){
	String writer=rs.getString("writer");
	String subject=rs.getString("subject");
	String content=rs.getString("content");
	
      out.write("\r\n");
      out.write("\t<h2>글수정</h2>\r\n");
      out.write("\t<form name=\"editForm\" method=\"post\">\r\n");
      out.write("\t  <table border=\"1\">\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t      <td>글쓴이</td>\r\n");
      out.write("\t      <td><input type=\"text\" name=\"writer\" value=\"");
      out.print(writer);
      out.write("\" size=\"20\"></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t      <td>글제목</td>\r\n");
      out.write("\t      <td><input type=\"text\" name=\"subject\" value=\"");
      out.print(subject);
      out.write("\" size=\"50\"></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t      <td>글내용</td>\r\n");
      out.write("\t      <td>\r\n");
      out.write("\t        <textarea name=\"content\" rows=\"10\" cols=\"50\">");
      out.print(content );
      out.write("</textarea>\r\n");
      out.write("\t      </td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t      <td>암호</td>\r\n");
      out.write("\t      <td><input type=\"password\" name=\"pw\" size=\"20\"></td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t    <tr>\r\n");
      out.write("\t      <td colspan=\"2\" align=\"center\">\r\n");
      out.write("\t        <input type=\"button\" value=\"글수정\" onclick=\"javaScript:check()\">\r\n");
      out.write("\t        <input type=\"button\" value=\"이전으로\" onclick=\"history.back()\">\r\n");
      out.write("\t        <a href=\"list.jsp\">리스트</a>\r\n");
      out.write("\t      </td>\r\n");
      out.write("\t    </tr>\r\n");
      out.write("\t  </table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
 
}//while-end

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
