/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-02-08 07:47:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch05_005ftemplate.ex03;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    h2{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    table{\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("    <script>\r\n");
      out.write("    function openDaumPostcode(){\r\n");
      out.write("      new daum.Postcode({\r\n");
      out.write("         oncomplete:function(data){\r\n");
      out.write("            document.getElementById('zipcode').value=data.zonecode;\r\n");
      out.write("            document.getElementById('addr').value=data.address;\r\n");
      out.write("          }\r\n");
      out.write("         \r\n");
      out.write("      }).open();\r\n");
      out.write("   }//openDaumPostcode()---\r\n");
      out.write("  </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <h2>회원가입</h2>\r\n");
      out.write("    <form method=\"post\" action=\"\">\r\n");
      out.write("      <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>ID</td>\r\n");
      out.write("          <td><input type=\"text\" name=\"id\" size=\"20\" placeholder=\"id입력\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>패스워드</td>\r\n");
      out.write("          <td><input type=\"password\" name=\"pw\" size=\"20\" placeholder=\"패스워드입력\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>이름</td>\r\n");
      out.write("          <td><input type=\"text\" name=\"name\" size=\"20\" placeholder=\"이름입력\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>전화번호</td>\r\n");
      out.write("          <td>\r\n");
      out.write("            <select name=\"tel\">\r\n");
      out.write("              <option value=\"010\">010</option>\r\n");
      out.write("              <option value=\"018\">018</option>\r\n");
      out.write("              <option value=\"017\">017</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            -\r\n");
      out.write("            <input type=\"text\" name=\"tel2\" size=\"4\" onKeyUp=\"if(this.value.length==4) tel3.focus()\">\r\n");
      out.write("            -\r\n");
      out.write("            <input type=\"text\" name=\"tel3\" size=\"4\">\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>이메일</td>\r\n");
      out.write("          <td>\r\n");
      out.write("          <input type=\"text\" name=\"email\" size=\"7\">\r\n");
      out.write("          @\r\n");
      out.write("          <input type=\"text\" name=\"email2\" size=\"7\" placeholder=\"직접입력\">\r\n");
      out.write("          <select name=\"email3\">\r\n");
      out.write("            <option value=\"@naver.com\">naver.com</option>\r\n");
      out.write("            <option value=\"@daum.net\">daum.net</option>\r\n");
      out.write("            <option value=\"@nate.com\">nate.com</option>\r\n");
      out.write("          </select>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>우편번호</td>\r\n");
      out.write("          <td>\r\n");
      out.write("          <input type=\"text\" name=\"zipcode\" id=\"zipcode\" size=\"7\">\r\n");
      out.write("          <input type=\"button\" value=\"주소찾기\" onclick=\"openDaumPostcode()\">\r\n");
      out.write("          <button type=\"button\" onclick=\"openDaumPostcode()\"><img src=\"../../imgs/find.gif\" alt=\"주소찾기\"></button>\r\n");
      out.write("          </td>\r\n");
      out.write("          \r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>주소</td>\r\n");
      out.write("          <td><input type=\"text\" name=\"addr\" id=\"addr\" size=\"20\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>상세주소</td>\r\n");
      out.write("          <td><input type=\"text\" name=\"addr2\" size=\"20\"></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td colspan=\"2\" align=\"center\">\r\n");
      out.write("            <input type=\"submit\" value=\"회원가입\">\r\n");
      out.write("            <input type=\"reset\" value=\"취소\">\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("    </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
