/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-02-09 01:56:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch07_005fsession.ex02;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/ch07_session/ex02/menu.jsp", Long.valueOf(1644370465932L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>cart.jsp</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

request.setCharacterEncoding("UTF-8");

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<h2>구매할 CD를 고르세요</h2>\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("  <select name=\"item\">\r\n");
      out.write("    <option value=\"임영웅CD\" selected>임영웅CD</option>\r\n");
      out.write("    <option value=\"허각CD\" selected>허각CD</option>\r\n");
      out.write("    <option value=\"김필CD\" selected>김필CD</option>\r\n");
      out.write("    <option value=\"아이유CD\" selected>아이유CD</option>\r\n");
      out.write("    <option value=\"김범수CD\" selected>김범수CD</option>\r\n");
      out.write("    <option value=\"백지영CD\" selected>백지영CD</option>\r\n");
      out.write("    <option value=\"나얼CD\" selected>나얼CD</option>\r\n");
      out.write("  </select>\r\n");
      out.write("  <input type=\"hidden\" name=\"step\" value=\"add\"><!-- 장바구니에 넣기 -->\r\n");
      out.write("  <input type=\"submit\" value=\"선택\">\r\n");
      out.write("</form>");
      out.write('\r');
      out.write('\n');

String step=request.getParameter("step"); //menu.jsp, remove.jsp
String item=request.getParameter("item");
Vector vec=null; //변수
if(item != null){//선택한 상품 있으면
	vec=(Vector)session.getAttribute("cart");
	if(vec==null){//처음 물건을 선택한 경우이면 
		vec=new Vector();
		vec.add(item); //장바구니에 상품 넣기
		session.setAttribute("cart", vec);
	}else{//장바구니에 내용이 있을때, 장바구니에 추가
		if(step.equals("add")){//장바구니에 넣는 작업
			vec.add(item);
		}else if(step.equals("remove")){//장바구니에서 상품 제거하는 작업
			vec.remove(item);
		}
	}//else-end
	out.println("쇼핑 카트에 담긴 물건(CD)<br>");
	for(int i=0;i<vec.size();i++){
		out.println((i+1)+":"+vec.get(i).toString()+"<br>");
	}
	
      out.write("\r\n");
      out.write("\t현재 카트에 모두 ");
      out.print(vec.size() );
      out.write("개가 담겨 있습니다\r\n");
      out.write("\t");

	if(vec.size()>0){//장바구니에 물건이 들어있으면
		
      out.write("\r\n");
      out.write("\t\t  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "remove.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t");

	}//if-end
}//if-end

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
