/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-02-11 06:51:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch11_005fboard_005fre;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <title>writeForm.jsp</title>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  h2{text-align: center;}\r\n");
      out.write("  table{margin:auto; width:60%;}\r\n");
      out.write("  </style>\r\n");
      out.write("  <script src=\"//code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  function check(){//데이터 입력여부 체크\r\n");
      out.write("\t  if($('#name').val()==''){\r\n");
      out.write("\t\t  alert(\"이름을 입력 하세요\");\r\n");
      out.write("\t\t  $('#name').focus();\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if($('#subject').val()==''){\r\n");
      out.write("\t\t  alert(\"글제목을 입력 하세요\");\r\n");
      out.write("\t\t  $('#subject').focus();\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if($('#content').val()==''){\r\n");
      out.write("\t\t  alert(\"글내용을 입력 하세요\");\r\n");
      out.write("\t\t  $('#content').focus();\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if($('#pw').val()==''){\r\n");
      out.write("\t\t  alert(\"암호를 입력 하세요\");\r\n");
      out.write("\t\t  $('#pw').focus();\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  return true;\r\n");
      out.write("  }\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <h2>게시판글쓰기</h2>\r\n");
      out.write(" <table>\r\n");
      out.write("   <tr>\r\n");
      out.write("     <td align=\"right\">\r\n");
      out.write("       <a href=\"list.jsp?page=1\">리스트</a>\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write(" </table>\r\n");
      out.write(" <form name=\"myForm\" method=\"post\" action=\"writePro.jsp\" onSubmit=\"return check()\">\r\n");
      out.write("   <table border=\"1\">\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td>이름</td>\r\n");
      out.write("       <td><input type=\"text\" name=\"name\" id=\"name\" size=\"20\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td>글제목</td>\r\n");
      out.write("       <td><input type=\"text\" name=\"subject\" id=\"subject\" size=\"20\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td>글내용</td>\r\n");
      out.write("       <td>\r\n");
      out.write("       <textarea name=\"content\" id=\"content\" rows=\"10\" cols=\"50\"></textarea>\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td>암호</td>\r\n");
      out.write("       <td><input type=\"password\" name=\"pw\" id=\"pw\" size=\"20\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td colspan=\"2\" align=\"center\">\r\n");
      out.write("         <input type=\"submit\" value=\"글쓰기\">\r\n");
      out.write("         <input type=\"reset\" value=\"취소\">\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("   </table>\r\n");
      out.write(" </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
