/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-02-21 01:01:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boardmysql;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class writeForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');

request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("  <title>Insert title here</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("  <script src=\"//code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("</head>\r\n");

if(session.getAttribute("id")==null){
	out.println("<h2>로그인을 해야 글쓰기가 가능합니다</h2>");
	return;
}
int num=0; //변수
int ref=1; //글 그룹
int re_step=0; //글 순서
int re_level=0; //답글 깊이
if(request.getParameter("num")!=null){
	//답글이면
	num=Integer.parseInt(request.getParameter("num"));
	ref=Integer.parseInt(request.getParameter("ref"));
	re_step=Integer.parseInt(request.getParameter("re_step"));
	re_level=Integer.parseInt(request.getParameter("re_level"));
	
}

      out.write("\r\n");
      out.write("<body>\r\n");

if(num==0){

      out.write("\r\n");
      out.write("<h2>글쓰기</h2>\r\n");
	
}else{

      out.write("\r\n");
      out.write("<h2>답글쓰기</h2>\r\n");
	
}

      out.write("\r\n");
      out.write("<form name=\"wirteForm\" method=\"post\" action=\"writePro.jsp\" onSubmit=\"return check()\">\r\n");
      out.write("  <input type=\"hidden\" name=\"num\" value=\"");
      out.print(num);
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"ref\" value=\"");
      out.print(ref);
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"re_step\" value=\"");
      out.print(re_step);
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" name=\"re_level\" value=\"");
      out.print(re_level);
      out.write("\">\r\n");
      out.write("  <table>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td colspan=\"2\" align=\"right\">\r\n");
      out.write("        <a href=\"list.jsp\">리스트</a>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>이름</td>\r\n");
      out.write("      <td><input type=\"text\" name=\"writer\" id=\"writer\" size=\"30\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>글제목</td>\r\n");
      out.write("      <td>\r\n");
      out.write("      ");

      if(request.getParameter("num")==null){ //원글
    	  
      out.write("\r\n");
      out.write("    \t  <input type=\"text\" name=\"subject\" id=\"subject\" size=\"50\">\r\n");
      out.write("    \t  ");
 
      }else{ //답글
    	  
      out.write("\r\n");
      out.write("    \t  <input type=\"text\" name=\"subject\" id=\"subject\" size=\"50\" value=\"[답글]\">\r\n");
      out.write("    \t  ");
 
      }//else-end
      
      out.write("\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>글내용</td>\r\n");
      out.write("      <td>\r\n");
      out.write("      <textarea name=\"content\" id=\"content\" rows=\"10\" cols=\"50\"></textarea>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>암호</td>\r\n");
      out.write("      <td><input type=\"password\" name=\"pw\" id=\"pw\" size=\"20\"></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td colspan=\"2\" align=\"center\">\r\n");
      out.write("      ");

      if(num==0){ //원글
    	  
      out.write("\r\n");
      out.write("    \t  <input type=\"submit\" value=\"글쓰기\">\r\n");
      out.write("    \t  ");

      }else{ //답글
    	  
      out.write("\r\n");
      out.write("    \t  <input type=\"submit\" value=\"답글쓰기\">\r\n");
      out.write("    \t  ");

      }//else-end
      
      out.write("\r\n");
      out.write("      <input type=\"reset\" value=\"다시쓰기\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
