/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-04 08:07:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import shopdb.*;
import java.util.*;

public final class cartList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/shop/bottom.jsp", Long.valueOf(1646358840563L));
    _jspx_dependants.put("/shop/top.jsp", Long.valueOf(1646358289390L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      shopdb.CartMgr cartMgr = null;
      synchronized (session) {
        cartMgr = (shopdb.CartMgr) _jspx_page_context.getAttribute("cartMgr", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (cartMgr == null){
          cartMgr = new shopdb.CartMgr();
          _jspx_page_context.setAttribute("cartMgr", cartMgr, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

OrderDTO orderDTO=null;
ProductDTO productDTO=null;
ProductDAO productDAO=null;
Hashtable hcart=null;

try{
	productDAO=ProductDAO.getDao(); //dao객체 얻기
	if(session.getAttribute("memId")==null){ //로그인상태가 아니면
		response.sendRedirect("loginForm.jsp"); //로그인으로 간다
	}else{ //로그인상태이면
		
      out.write("\r\n");
      out.write("\t\t<html>\r\n");
      out.write("\t\t  <head>\r\n");
      out.write("\t\t    <link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write(" \t\t\t<script src=\"//code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write(" \t\t\t<script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("\t\t  </head>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t  <body bgcolor=\"#996600\" topmargin=\"100\">\r\n");
      out.write("\t\t    ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");

String memId=(String)session.getAttribute("memId");
String log="";
String mem="";
if(memId==null){
	log="<a href='loginForm.jsp'>로그인</a>";
	mem="<a href='inputForm.jsp'>회원가입</a>";
}else{ //로그인 상태이면
	log="<a href='logOut.jsp'>로그아웃</a>";
	mem="<a href='updateMember.jsp'>내정보수정</a>";
}

      out.write("\r\n");
      out.write("<table width=\"80%\" align=\"center\" bgcolor=\"#ffff99\">\r\n");
      out.write("  <tr bgcolor=\"#ffcc00\">\r\n");
      out.write("    <td align=\"center\"><b>");
      out.print(log);
      out.write("</b></td>\r\n");
      out.write("    <td align=\"center\"><b>");
      out.print(mem);
      out.write("</b></td>\r\n");
      out.write("    <td align=\"center\"><b><a href=\"productList.jsp\">상품목록</a></b></td>\r\n");
      out.write("    <td align=\"center\"><b><a href=\"cartList.jsp\">장바구니</a></b></td>\r\n");
      out.write("    <td align=\"center\"><b><a href=\"orderList.jsp\">구매목록</a></b></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("\t\t    <table width=\"80%\" bgcolor=\"#ffff99\">\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <td align=\"center\" bgcolor=\"#ffffcc\">\r\n");
      out.write("\t\t          <table width=\"95%\" bgcolor=\"#ffff99\" border=\"1\">\r\n");
      out.write("\t\t            <tr bgcolor=\"#996600\">\r\n");
      out.write("\t\t              <td><font color=\"#FFFFFF\">제품</font></td>\r\n");
      out.write("\t\t              <td><font color=\"#FFFFFF\">수량</font></td>\r\n");
      out.write("\t\t              <td><font color=\"#FFFFFF\">가격</font></td>\r\n");
      out.write("\t\t              <td><font color=\"#FFFFFF\">수정/삭제</font></td>\r\n");
      out.write("\t\t              <td><font color=\"#FFFFFF\">조회</font></td>\r\n");
      out.write("\t\t            </tr>\r\n");
      out.write("\t\t            ");

		              int totalPrice=0; //총금액
		              hcart=cartMgr.getCartList(); //장바구니내용 모두 가져온다
		              if(hcart.size()==0){ //장바구니에 내용이 없으면
		            	  out.println("장바구니 내용이 없습니다");
		              }else{ //장바구니에 내용이 있으면
		            	  out.println("<tr><td align=center colspan=5>장바구니에 들어있는 상품내역</td></tr>");
		              	  Enumeration hcartKeys=hcart.keys();
		              	  while(hcartKeys.hasMoreElements()){ //자료가 있는동안 반복처리
		              		  orderDTO=(OrderDTO)hcart.get(hcartKeys.nextElement());
		              	  	  productDTO=productDAO.getProduct(orderDTO.getPro_no());
		              	  	  int price=productDTO.getPrice(); //가격
		              	  	  int quantity=Integer.parseInt(orderDTO.getQuantity()); //수량
		              	  	  int subTotal=price*quantity; //하나의 물건을 1이상 샀을때
		              	  	  totalPrice += subTotal; //총금액 구한다
		              	  	  
      out.write("\r\n");
      out.write("\t\t              \t  \t  <form method=\"post\" action=\"cartPro.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"pro_no\" value=\"");
      out.print(productDTO.getPro_no());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"flag\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"state\" value=\"2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(productDTO.getName() );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"quantity\" value=\"");
      out.print(orderDTO.getQuantity());
      out.write("\" size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>");
      out.print(subTotal+"" );
      out.write("</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input type=\"button\" value=\"cart수정\" onClick=\"javaScript:cartUpdate(this.form)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input type=\"button\" value=\"cart삭제\" onClick=\"javaScript:cartDelete(this.form)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javaScript:productDetail('");
      out.print(productDTO.getCode());
      out.write("')\">상세보기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t              \t  \t  ");

		              	  }//while-end
		              	  
      out.write("\r\n");
      out.write("\t\t              \t  <tr>\r\n");
      out.write("\t\t              \t    <td colspan=\"4\" align=\"right\">\r\n");
      out.write("\t\t              \t            총 금액:");
      out.print(totalPrice );
      out.write("\r\n");
      out.write("\t\t              \t    </td>\r\n");
      out.write("\t\t              \t    <td align=\"center\">\r\n");
      out.write("\t\t              \t      <a href=\"orderPro.jsp\">주문하기</a>\r\n");
      out.write("\t\t              \t    </td>\r\n");
      out.write("\t\t              \t  </tr>\r\n");
      out.write("\t\t              \t  ");
 
		              }//else-end
		            
      out.write("\r\n");
      out.write("\t\t          </table>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t    </table>\r\n");
      out.write("\t\t      <form name=\"detail\" method=\"post\" action=\"productDetail.jsp\">\r\n");
      out.write("\t\t        <input type=\"hidden\" name=\"code\">\r\n");
      out.write("\t\t      </form>\r\n");
      out.write("\t\t    ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<table width=\"80%\" align=\"center\" bgcolor=\"#FFF99\">\r\n");
      out.write("  <tr bgcolor=\"#ffcc00\">\r\n");
      out.write("    <td align=\"center\" width=\"90%\">\r\n");
      out.write("      <b>Simple Shopping Mall에 오신것을 환영 합니다</b>\r\n");
      out.write("    </td>\r\n");
      out.write("    <td align=\"center\">\r\n");
      out.write("      <a href=\"../admin/Index.jsp\">관리자</a>\r\n");
      out.write("    </td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("\t\t  </body>\r\n");
      out.write("\t\t</html>\r\n");
      out.write("\t\t");

	}//else-end
}catch(Exception ex){
	out.println("cartList.jsp 예외:"+ex);
}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
