/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2022-03-31 06:54:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.faqboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faqoperationpolicy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>faqoperationpolicy.jsp</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#faq-detail-title{\r\n");
      out.write("  display: block;\r\n");
      out.write("  font-size: 1.3rem;\r\n");
      out.write("  color: #868e96;\r\n");
      out.write("  margin-bottom: 0.4em;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("#faq-detail-category{\r\n");
      out.write("  display: block;\r\n");
      out.write("  font-size: 1.3rem;\r\n");
      out.write("  color: #868e96;\r\n");
      out.write("  margin-bottom: 0.4em;\r\n");
      out.write("  font-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <h2 id=\"faq-detail-title\">\r\n");
      out.write("    <span id=\"faq-detail-category\">운영정책</span>\r\n");
      out.write("    중고거래 운영정책\r\n");
      out.write("  </h2>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"faq-detail-content\">\r\n");
      out.write("   <p><br></p>\r\n");
      out.write("   <p>XXX은 동네 이웃 간의 연결을 도와 따뜻하고 활발한 교류가 있는 지역 사회를 만들기 위해 노력하고 있어요.</p>\r\n");
      out.write("   <p>우리는 신뢰, 존중, 윤리를 서비스의 중요한 가치라고 생각해요. 당근마켓과 당근마켓을 사용하는 이웃 모두가 동참하여 이 가치를 지키기 위해 최선을 다하고 있어요. 따뜻하고 믿을 수 있는 거래 문화를 함께 만들어가요.</p><p><br></p>\r\n");
      out.write("   <h2><strong>가까운 이웃과의 만남이 따뜻함이 될 수 있도록 거래매너를 지켜요.</strong>\r\n");
      out.write("   </h2><ul><li>서로 존중하고 배려해요. 존댓말로 솔직하게 대화해요.</li>\r\n");
      out.write("   <li>모두의 시간은 소중해요. 약속은 반드시 지켜요.</li>\r\n");
      out.write("   <li>절대로 중간에 연락 끊기는 일이 없도록 해요.</li>\r\n");
      out.write("   <li>언제나 따뜻한 인사로 시작하고 마무리해요.</li>\r\n");
      out.write("   <li>늦은 시간, 특히 모두가 자고 있는 새벽 시간에는 채팅을 자제해 주세요.</li>\r\n");
      out.write("   <li>택배 거래보다는 만나서 직거래하기로 해요.</li>\r\n");
      out.write("   <li>이웃과의 거래는 만 14세 이상 부터 하기로 해요.</li>\r\n");
      out.write("   </ul><p><br></p>\r\n");
      out.write("   <h3><strong>구매자, 판매자가 함께 노력하여 신뢰를 만들어요.</strong></h3>\r\n");
      out.write("   <p><strong>구매할 때:</strong></p>\r\n");
      out.write("   <ul><li>판매글을 꼼꼼히 읽고 질문해요.</li>\r\n");
      out.write("   <li>미리 신중하게 고민한 뒤 판매자와 거래 약속을 잡아요.</li>\r\n");
      out.write("   <li>직거래할 땐 판매자에게 가까운 장소에서 만나요.</li>\r\n");
      out.write("   <li>지나치게 가격을 깎지 않아요. 판매자의 가격 책정을 존중해요.</li>\r\n");
      out.write("   <li>가격제안불가 게시글에는 가격 할인을 요구하지 않아요.</li>\r\n");
      out.write("   <li>물건 금액에 맞게 현금을 미리 준비해요.</li>\r\n");
      out.write("   <li>나눔을 받으면 따뜻한 감사인사로 마무리해요.</li>\r\n");
      out.write("   </ul><p><br></p><p><strong>판매할 때:</strong></p><ul>\r\n");
      out.write("   <li>직접 촬영한 사진으로 판매글을 작성해요. 실제 물품 사진이 아닌 경우 오해가 생길 수 있어요.</li>\r\n");
      out.write("   <li>물품에 대한 설명을 자세히 써요. 특히, 주요 하자에 대한 내용은 꼭 명시하기로 해요.</li>\r\n");
      out.write("   <li>판매하기 전에 깨끗하게 세탁 또는 관리해요. 사용감이 있더라도 청결한 물건은 서로의 기분을 좋게 한답니다.</li>\r\n");
      out.write("   <li>거래 약속이 잡았다면 게시글의 상태를 '예약중'으로 바꿔요.</li>\r\n");
      out.write("   <li>예약한 이웃이 있다면 그 분에게 판매해요. 예약 파기는 서로의 신뢰를 무너뜨리는 행동이에요.</li>\r\n");
      out.write("   <li>당근마켓에서 구매한 상품을 다시 팔아야 한다면, 반드시 재판매 사유와 함께 적어주세요. 구매가격과 동일하거나 더 저렴한 가격으로만 판매할 수 있어요.</li></ul><p><br></p>\r\n");
      out.write("   <p><strong>직거래할 때:</strong></p><ul><li>누구나 찾기 쉽고 안전한 공공장소에서 만나요. 밝고 사람이 많은 장소에서 거래해요.</li>\r\n");
      out.write("   <li>서로의 집 앞까지 오더라도 집 밖에서 거래하기로 해요. 우리 동네 이웃 중 누군가는 남의 공간에 들어가는 것을 꺼려할 수 있어요.</li>\r\n");
      out.write("   <li>혹시 차를 타고 이동하셨나요? 먼저 차에서 내려 인사를 건네보세요. 좁은 차보다는 넓은 공간에서 서로 물건 상태를 확인하고 거래해요.</li>\r\n");
      out.write("   <li>판매중인 물건도 여전히 판매자의 소중한 물품이에요. 구매자는 판매자를 배려하며 물건 상태를 조심히 확인해요.</li>\r\n");
      out.write("   <li>물건의 정보는 판매자가 누구보다 잘 알고 있어요. 구매자가 물품의 동작, 착용 등을 궁금해할 때, 판매자가 직접 시연하거나 착용하여 구매자에게 자세하게 보여주면 좋아요.</li>\r\n");
      out.write("   <li>높은 가격의 물품은 판매자, 구매자 모두 더 신중하게 거래해요.</li><li>지금 이 거래가 상대방의 첫 중고거래일 수도 있어요. 중고거래에 익숙하지 않더라도 배려하며 거래해요. 첫 기억을 따뜻하게 만들어주세요.</li>\r\n");
      out.write("   <li>우리 주변에는 정말 다양한 이웃이 있어요. 언제나 나와 다른 사람을 만나게 될 거예요. 성별, 나이, 종교, 혼인 여부, 인종, 장애 등 이웃의 다양성을 존중해 주세요.</li>\r\n");
      out.write("   <li>온라인으로 연결되어 만났지만, 동네 어디서나 마주칠 수 있는 이웃이라는 사실을 기억해요.</li>\r\n");
      out.write("   <li>물품의 상태를 꼼꼼하게 확인해주세요. 직접 만나 구매한 경우 사용감으로 인한 환불은 어려워요.</li>\r\n");
      out.write("   <li>거래 관련 모든 문제는 중고거래 게시판 거래 및 환불 정책을 따르고 있어요. 문제가 발생했을 때는 해당 정책을 확인해 주세요.</li>\r\n");
      out.write("   </ul><p><br></p>\r\n");
      out.write("   <p><strong>비대면 거래할 때:</strong></p>\r\n");
      out.write("   <p>먼저, 당근마켓에서는 직거래를 권장하고 있어요!</p>\r\n");
      out.write("   <p>부득이하게 택배 또는 문고리 거래 등 비대면 거래가 필요하신 경우 아래 내용을 꼭 확인해주세요.</p>\r\n");
      out.write("   <ul><li>파손 가능성이 있는 물품은 되도록 직접 만나서 거래해주세요. 만약, 직거래가 불가한 경우라면 파손되지 않도록 완충재 사용해주세요.</li>\r\n");
      out.write("   <li>판매 글에서 확인이 되지 않는 부분이 있다면 판매자에게 사진 촬영을 요청해 꼼꼼하게 확인해주세요.</li>\r\n");
      out.write("   </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
